services:
  - type: web
    name: self-healing-selenium
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update
      apt-get install -y chromium-driver
    startCommand: python run.py