name: Self-Healing Selenium Tests

on:
  push:
    branches: [main]
  workflow_dispatch:  # allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pytest-html
        run: pip install pytest-html

      - name: Run tests
        run: pytest tests/test_login.py -v --html=docs/index.html --self-contained-html

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs